WIP: Feature/eks addon profile
weaveworks/profiles-catalog pull request #179
Opened 2022-09-06 19:09 UTC by jwlai

Need some feedback for this chart. It installs properly but there are some items that I'm not too clear about.

2022-09-06 19:16 UTC, steve-fraser commented
The autoscaler currently is configured differently based upon MachinePool and MachineDeplyoment respectively. In, the past CAPI basically fought the autoscaler group trying to reconcile the MachinePool replicas (https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2022) . I would consider keeping that out of this chart, but here is a few I would put in there:
(aws-node-termination-handler) https://github.com/filecoin-project/gitops-profile-catalog/tree/main/charts/aws-node-term-handler
(aws-ebs-csi-driver) https://github.com/filecoin-project/gitops-profile-catalog/tree/main/charts/aws-ebs-csi-driver
(aws-load-balancer-controller) https://github.com/filecoin-project/gitops-profile-catalog/tree/main/charts/aws-load-balancer-controller

2022-09-06 19:45 UTC, jwlai commented
Since we're attaching multiple charts in one "profile", the chart.yaml annotation is fit for this design. Is this a question for engineering? (Kevin?)

i.e. One of the charts Steve mentioned has the "Operator" annotation, others have different "Upstream Project" Urls.

2022-09-13 22:32 UTC, darrylweaver commented
aws-node-termination-handler would not be needed for an AWSManagedMachinePool see:
https://cluster-api-aws.sigs.k8s.io/topics/machinepools.html#awsmanagedmachinepool
and
https://github.com/aws/aws-node-termination-handler#project-summary
see the end of the project summary:

> You can run the termination handler on any Kubernetes cluster running on AWS, including self-managed clusters and those created with Amazon Elastic Kubernetes Service. If you're using EKS managed node groups, you don't need the aws-node-termination-handler.

So we would need to be able to turn it on or off, depending on the EKS cluster's objects in the template.

I would suggest we have a global parameter for turning on and off each of the subcharts.
An example would be the answer to this question showing how they do it for elk-stack charts:
https://stackoverflow.com/questions/55338147/disabling-subcharts-in-custom-helm-chart

Then we can include or exclude the subcharts with a simple parameter at the top level of values.yaml.

The issue with multiple sources.  Maybe it makes sense to have unique sources.  It may make sense to put the storage driver into it's own chart as it is a different source.
Then bundle the add-ons from the eks-charts repo together into one chart using the conditions to turn them on or off.

2022-10-03 21:17 UTC, darrylweaver requested changes
Can the example ARN values be commented out?

We are not testing on EKS, which should be added ideally, but we could defer that to another Asana task.

2022-10-03 21:17 UTC, darrylweaver commented on charts/karpenter/values.yaml
> +      eks.amazonaws.com/role-arn: 'arn:aws:iam::123456789012:role/MyRoleName'
Can this also be commented out?

2022-12-07 09:27 UTC, darrylweaver approved these changes

2023-08-01 09:32 UTC, merged