Upgrade policy profile to v2.4.0
weaveworks/profiles-catalog pull request #212
Opened 2023-05-14 15:36 UTC by serboctor

This PR upgrades the profiles to policy-agent 2.4.0 as-well-as upgrading the Kustomization and GitRepository to v1 and removing deprecated fields.

2023-05-31 10:44 UTC, waleedhammam submitted a review, later dismissed

2023-06-06 13:23 UTC, darrylweaver requested changes
Please enable testing by adding the annotation to the Chart.yaml.

2023-06-06 13:23 UTC, darrylweaver commented on charts/weave-policy-agent/Chart.yaml
Could you enable testing for this Helm chart please.
If you add:
```
annotations:
  "weave.works/profile-ci": |
    - "kind"
```
That will test that the profile installs correctly on a Kind cluster

2023-06-06 15:59 UTC, darrylweaver submitted a review, later dismissed

2023-07-16 07:54 UTC, waleedhammam approved these changes

2023-08-07 17:30 UTC, merged